name: Build Porymap
permissions:
  contents: write

on:
  push:
    branches:
      - master
      - dev
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build-macos:
    strategy:
      matrix:
        os: [macos-latest, macos-13]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set Build Name
        run: echo "BUILD_NAME=porymap-${{ matrix.os }}" >> $GITHUB_ENV

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.2'
          modules: 'qtcharts'
          cache: 'true'

      - name: Configure
        run: qmake -config release porymap.pro

      - name: Compile
        run: make

      - name: Create Disk Image
        run: macdeployqt porymap.app -dmg

      - name: Prep Release Directory
        run: |
          mkdir ${{ env.BUILD_NAME }}
          cp porymap.dmg ${{ env.BUILD_NAME }}/porymap.dmg
          cp RELEASE-README.txt ${{ env.BUILD_NAME }}/README.txt

      - name: Bundle Release Directory
        run: zip -r ${{ env.BUILD_NAME }}.zip ${{ env.BUILD_NAME }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.BUILD_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
